[project]
name = "po-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "camelot-py[cv]>=1.0.9",
    "numpy>=2.3.3",
    "pdfplumber>=0.11.7",
    "pymupdf>=1.26.5",
    "tabula-py>=2.10.0",
]
